#!/bin/bash

if ![ -d /path/to/directory ]; then
    echo "Making venv..."
    python3.12 -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
fi

echo "Running tests..."
python -m pytest tests/

# $? stores exit value of the last command
if [ $? -ne 0 ]; then
    echo "Tests failed. Commit aborted."
    exit 1
fi

echo "Tests passed!"
exit 0
